name: Build & Push

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Nix Config
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            release_suffix: ubuntu
    runs-on: ${{ matrix.os }}
    steps:
      - run: sudo rm -rf /opt&
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: ymstnt-dotfiles
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: x86_64-linux Build
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L .#nixosConfigurations.{andromeda,cassiopeia}

      - name: Deploy
        run: |
          cachix push ymstnt-dotfiles ./result*
